### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.TSFBuilder

### ISSUE THREAD

**Issue by wdaas** [redisson/redisson#3476]
keep getting this error when i try this
Config.fromYAML(PropertiesUtil.getResourceAsFile(REDISSON_RESOURCE_NAME));

the exception is 
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/TSFBuilder
	at org.redisson.config.ConfigSupport.<init>(ConfigSupport.java:92)
	at org.redisson.config.Config.fromYAML(Config.java:661)
	at org.redisson.config.Config.fromYAML(Config.java:657)

when I try to look at the code can't find usage for TSFBuilder at class ConfigSupport

**Comment by mrniko** [comment]
Check for absence of two jackson libs in classpath with different versions

**Comment by wdaas** [comment]
thanks @mrniko 

the problem was that redis 3.14.0 have dependency to jackson-dataformat-yaml.jar and it import version 2.11.1
but in our project we work with Jackson-core 2.7.6 .

by add explicitly at mvn file dependency for version 2.7.6 for jackson-dataformat-yaml.jar we fix the issue.
