### ISSUE TITLE
NoClassDefFoundError after upgrading from 3.3.1 to 3.3.2

### ISSUE THREAD

**Issue by kubagruszka** [redisson/redisson#862]
I'm using redisson JSR107 implementation and after upgrading from version 3.3.1 to 3.3.2 I start to get following exception immediately:

```
Caused by: java.lang.NoClassDefFoundError: net/openhft/hashing/LongHashFunction 
	at org.redisson.misc.Hash.hashToBase64(Hash.java:43) 
	at org.redisson.jcache.JCache.getLockName(JCache.java:560) 
	at org.redisson.jcache.JCache.getLockedLock(JCache.java:744) 
	at org.redisson.jcache.JCache.put(JCache.java:809)
```

**Comment by jackygurui** [comment]
This looks like the required jar is missing

**Comment by asmaier** [comment]
I have the same issue in version 3.4.1:

    RedissonClient client = redissonNode.getRedisson();
    RLocalCachedMap<String, String> map = client.getLocalCachedMap("test", LocalCachedMapOptions.defaults());
    map.put("1", "value1");

throws 

    java.lang.NoClassDefFoundError: net/openhft/hashing/LongHashFunction
    at org.redisson.misc.Hash.hash(Hash.java:30)
    at org.redisson.RedissonLocalCachedMap.toCacheKey(RedissonLocalCachedMap.java:345)
    at org.redisson.RedissonLocalCachedMap.putAsync(RedissonLocalCachedMap.java:429)
    at org.redisson.RedissonMap.put(RedissonMap.java:202)

**Comment by asmaier** [comment]
Could the reason be that the dependency for openhft is missing in https://github.com/redisson/redisson/blob/master/redisson-all/pom.xml ?

**Comment by mrniko** [comment]
@asmaier You're correct dependency is missing for `redisson-all` module

**Comment by mrniko** [comment]
Fixed
