### ISSUE TITLE
Numerous RedisConnectionException :Can't aquire connection to...

### ISSUE THREAD

**Issue by nel10000** [redisson/redisson#2057]
Numerous RedisConnectionException occur in production environment for no apparent reason.
The same deployment is used in other production environments without problems.
The first guess would be a configuration or environmental issue.
### The stack trace is:
org.redisson.client.RedisConnectionException: Can't aquire connection to /10.222.222.54:7000
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:180) ~[redisson-2.2.12.jar:?]
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:24) ~[redisson-2.2.12.jar:?]
	at org.redisson.connection.balancer.LoadBalancerManagerImpl.getConnection(LoadBalancerManagerImpl.java:132) ~[redisson-2.2.12.jar:?]
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:367) ~[redisson-2.2.12.jar:?]
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:587) ~[redisson-2.2.12.jar:?]
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:393) ~[redisson-2.2.12.jar:?]
	at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:444) ~[redisson-2.2.12.jar:?]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.36.Final.jar:4.0.36.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]

### Steps to reproduce or test case
The error probably happens when trying to read data from Redis cluster as I see access to "SlaveConnectionPool". 
Please note we set an expiration time for each entry in the cache.

### Redisson configuration: 
{
   "clusterServersConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":1000,
      "timeout":1000,
      "retryAttempts":3,
      "retryInterval":1000,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "loadBalancer":{
         "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
      },
      "slaveSubscriptionConnectionMinimumIdleSize":1,
      "slaveSubscriptionConnectionPoolSize":25,
      "slaveConnectionMinimumIdleSize":50,
      "slaveConnectionPoolSize":800,
      "masterConnectionMinimumIdleSize":50,
      "masterConnectionPoolSize":800,
      "readMode":"SLAVE",
      "nodeAddresses":[
        "//10.222.222.55:7000",
        "//10.222.222.55:7001",
        "//10.222.222.54:7000",
        "//10.222.222.54:7001",
        "//10.222.222.53:7000",
        "//10.222.222.53:7001"
        ],
      "scanInterval":1000
   },
   "threads":0,
   "codec":null,
   "useLinuxNativeEpoll":false,
   "eventLoopGroup":null
}

**Comment by mrniko** [comment]
I suggest you to update Redisson to 2.15.2 / 3.10.6 version. Starting from 2.15.0 version it provides correct implementation of connection ping with `pingConnectionInterval`  setting. Also try to set slaveConnectionPoolSize = slaveConnectionMinimumIdleSize.

**Comment by nel10000** [comment]
Thank you for the reply.
When trying to update Redisson to 2.15.2 / 3.10.6, there are numerous compilation errors.
Is there a migration guide?
Regarding setting the "slaveConnectionPoolSize = slaveConnectionMinimumIdleSize", do you suggest in my case to use the higher or lower values for both? e.g. 800 or 50?
Regrading the following sentence: "Setting this setting to true would help to avoid broken connections" - to which setting does it refer to?

**Comment by mrniko** [comment]
> Is there a migration guide?

I'm afraid no. 3.10.6 requires java 1.8. What is your current JVM version?

> Regarding setting the "slaveConnectionPoolSize = slaveConnectionMinimumIdleSize", do you suggest in my case to use the higher or lower values for both? e.g. 800 or 50?

I would suggest to start with 50

> Regrading the following sentence: "Setting this setting to true would help to avoid broken connections" - to which setting does it refer to?

to `pingConnectionInterval` setting

**Comment by nel10000** [comment]
I'm working with Java 1.8 so no problem here.
The main errors I'm getting are related to non existing classes, such as RBucket, RMapCache, etc.

The deployment has been completed a few years ago, but if I remember correctly the values for the slaveConnectionPoolSize setting was determined following performance tests. Setting both to 800 will not  be advised?

**Comment by mrniko** [comment]
> The main errors I'm getting are related to non existing classes, such as RBucket, RMapCache, etc.

I'm afraid you're mistaken these classes are still present in Redisson. Please check your classpath.

> Setting both to 800 will not be advised?

I depends on your requirements.

**Comment by nel10000** [comment]
Thank you. The classes are still there indeed.
The solution for the non existing classes was to simply change to imports to the new package paths:
Switch from org.redisson.core to org.redisson.api.

**Comment by jackygurui** [comment]
> Thank you. The classes are still there indeed.
> The solution for the non existing classes was to simply change to imports to the new package paths:
> Switch from org.redisson.core to org.redisson.api.

Thank you for been an early and loyal user! Looks like you have been using Redisson since very early days.
